/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Dimension;

/**
 *
 * @author jimes
 */
public class FrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrPrincipal
     */
    public FrPrincipal() {
        initComponents();
       this.setExtendedState(this.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPaciente = new javax.swing.JMenu();
        mabmPaciente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mspacientesactivos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuComida = new javax.swing.JMenu();
        mabmComida = new javax.swing.JMenuItem();
        msComidasActivas = new javax.swing.JMenuItem();
        msComidasmenoresCalorias = new javax.swing.JMenuItem();
        MenuDieta = new javax.swing.JMenu();
        mabmdieta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mmsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nutricionista -G7");

        escritorio.setBackground(new java.awt.Color(55, 97, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nut.png"))); // NOI18N
        jLabel1.setToolTipText("");

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 858, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(0, 488, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuPaciente.setText("Paciente");
        MenuPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPacienteActionPerformed(evt);
            }
        });

        mabmPaciente.setText("A/B/M Paciente");
        mabmPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mabmPacienteActionPerformed(evt);
            }
        });
        MenuPaciente.add(mabmPaciente);
        MenuPaciente.add(jSeparator1);

        mspacientesactivos.setText("Mostrar Pacientes");
        mspacientesactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mspacientesactivosActionPerformed(evt);
            }
        });
        MenuPaciente.add(mspacientesactivos);

        jMenuItem2.setText("Buscar Pacientes por peso");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuPaciente.add(jMenuItem2);

        jMenuBar1.add(MenuPaciente);

        MenuComida.setText("Comida");

        mabmComida.setText("A/B/M Comida");
        mabmComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mabmComidaActionPerformed(evt);
            }
        });
        MenuComida.add(mabmComida);

        msComidasActivas.setText("Buscar Comidas Activas");
        msComidasActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msComidasActivasActionPerformed(evt);
            }
        });
        MenuComida.add(msComidasActivas);

        msComidasmenoresCalorias.setText("Buscar comidas menores a Calorias");
        msComidasmenoresCalorias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        msComidasmenoresCalorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msComidasmenoresCaloriasActionPerformed(evt);
            }
        });
        MenuComida.add(msComidasmenoresCalorias);

        jMenuBar1.add(MenuComida);

        MenuDieta.setText("Dieta");
        MenuDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDietaActionPerformed(evt);
            }
        });

        mabmdieta.setText("A/B/M Dieta");
        mabmdieta.setName(""); // NOI18N
        mabmdieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mabmdietaActionPerformed(evt);
            }
        });
        MenuDieta.add(mabmdieta);

        jMenuBar1.add(MenuDieta);

        jMenu1.setText("Salir");

        mmsalir.setText("Confirma que desea salir?");
        mmsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmsalirActionPerformed(evt);
            }
        });
        jMenu1.add(mmsalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPacienteActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPacienteActionPerformed

    private void mabmPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mabmPacienteActionPerformed
        FrPaciente fpaciente = new FrPaciente();
        escritorio.add(fpaciente);
        //codigo para centrar ventana
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = fpaciente.getSize();
        fpaciente.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        fpaciente.setVisible(true);
        escritorio.moveToFront(fpaciente);        // TODO add your handling code here:
        fpaciente.show();
    }//GEN-LAST:event_mabmPacienteActionPerformed

    private void MenuDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDietaActionPerformed

    }//GEN-LAST:event_MenuDietaActionPerformed

    private void mabmdietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mabmdietaActionPerformed

        FrDieta fdieta = new FrDieta();
        escritorio.add(fdieta);
        //codigo para centrar ventana
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = fdieta.getSize();
        fdieta.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------
        fdieta.setVisible(true);
        escritorio.moveToFront(fdieta);        // TODO add your handling code here:
        fdieta.show();

// TODO add your handling code here:
    }//GEN-LAST:event_mabmdietaActionPerformed

    private void mmsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmsalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_mmsalirActionPerformed

    private void mabmComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mabmComidaActionPerformed
        FrComida fcomida = new FrComida();
        escritorio.add(fcomida);
        //codigo para centrar ventana
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = fcomida.getSize();
        fcomida.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        fcomida.setVisible(true);
        escritorio.moveToFront(fcomida);        // TODO add your handling code here:
        fcomida.show();
    }//GEN-LAST:event_mabmComidaActionPerformed

    private void mspacientesactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mspacientesactivosActionPerformed
        FrBuscarPacientes fbp = new FrBuscarPacientes();
        escritorio.add(fbp);
        //codigo para centrar ventana
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = fbp.getSize();
        fbp.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        fbp.setVisible(true);
        escritorio.moveToFront(fbp);        // TODO add your handling code here:
        fbp.show();        // TODO add your handling code here:
    }//GEN-LAST:event_mspacientesactivosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        FrBuscarPacientesKilo fbpk = new FrBuscarPacientesKilo();
        escritorio.add(fbpk);
        //codigo para centrar ventana
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = fbpk.getSize();
        fbpk.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        fbpk.setVisible(true);
        escritorio.moveToFront(fbpk);        // TODO add your handling code here:
        fbpk.show();        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void msComidasActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msComidasActivasActionPerformed
    FrBuscarComidasActivas fbca = new FrBuscarComidasActivas();
        escritorio.add(fbca);
        //codigo para centrar ventana
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = fbca.getSize();
        fbca.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        fbca.setVisible(true);
        escritorio.moveToFront(fbca);        // TODO add your handling code here:
        fbca.show();        // TODO add your handling code here:
                // TODO add your handling code here:
    }//GEN-LAST:event_msComidasActivasActionPerformed

    private void msComidasmenoresCaloriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msComidasmenoresCaloriasActionPerformed
    FrBuscarComidasCalorias fbcc = new FrBuscarComidasCalorias();
        escritorio.add(fbcc);
        //codigo para centrar ventana
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = fbcc.getSize();
        fbcc.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        fbcc.setVisible(true);
        escritorio.moveToFront(fbcc);        // TODO add your handling code here:
        fbcc.show();        // TODO add your handling code here:
                // TODO add your handling code here:
    
        
        
        
    }//GEN-LAST:event_msComidasmenoresCaloriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuComida;
    private javax.swing.JMenu MenuDieta;
    private javax.swing.JMenu MenuPaciente;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mabmComida;
    private javax.swing.JMenuItem mabmPaciente;
    private javax.swing.JMenuItem mabmdieta;
    private javax.swing.JMenuItem mmsalir;
    private javax.swing.JMenuItem msComidasActivas;
    private javax.swing.JMenuItem msComidasmenoresCalorias;
    private javax.swing.JMenuItem mspacientesactivos;
    // End of variables declaration//GEN-END:variables
}
