/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Dimension;

/**
 *
 * @author jimes
 */
public class FrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrPrincipal
     */
    public FrPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAlumno = new javax.swing.JMenu();
        abmAlumno = new javax.swing.JMenuItem();
        mlistadoalumnos = new javax.swing.JMenuItem();
        mMateria = new javax.swing.JMenu();
        mmabmMat = new javax.swing.JMenuItem();
        mmMuestraAlxMat = new javax.swing.JMenuItem();
        mnotas = new javax.swing.JMenu();
        mmodificaNotas = new javax.swing.JMenuItem();
        mInscripciones = new javax.swing.JMenu();
        abminscripciones = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mmsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA GENERAL ADMINISTRATIVO");

        escritorio.setBackground(new java.awt.Color(55, 97, 140));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1141, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        MenuAlumno.setText("Alumno");
        MenuAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAlumnoActionPerformed(evt);
            }
        });

        abmAlumno.setText("A/B/M Alumno");
        abmAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmAlumnoActionPerformed(evt);
            }
        });
        MenuAlumno.add(abmAlumno);

        mlistadoalumnos.setText("Listado Alumnos Activos");
        mlistadoalumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlistadoalumnosActionPerformed(evt);
            }
        });
        MenuAlumno.add(mlistadoalumnos);

        jMenuBar1.add(MenuAlumno);

        mMateria.setText("Materia");

        mmabmMat.setText("A/B/M materia");
        mmabmMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmabmMatActionPerformed(evt);
            }
        });
        mMateria.add(mmabmMat);

        mmMuestraAlxMat.setText("Muestra Alumnos Inscriptos por materia");
        mmMuestraAlxMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmMuestraAlxMatActionPerformed(evt);
            }
        });
        mMateria.add(mmMuestraAlxMat);

        jMenuBar1.add(mMateria);

        mnotas.setText("Notas");
        mnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnotasActionPerformed(evt);
            }
        });

        mmodificaNotas.setText("Modificar Notas por Alumno");
        mmodificaNotas.setName(""); // NOI18N
        mmodificaNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmodificaNotasActionPerformed(evt);
            }
        });
        mnotas.add(mmodificaNotas);

        jMenuBar1.add(mnotas);

        mInscripciones.setText("Inscripciones");
        mInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mInscripcionesActionPerformed(evt);
            }
        });

        abminscripciones.setText("A/B/M Inscripciones");
        abminscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abminscripcionesActionPerformed(evt);
            }
        });
        mInscripciones.add(abminscripciones);

        jMenuBar1.add(mInscripciones);

        jMenu1.setText("Salir");

        mmsalir.setText("Confirma que desea salir?");
        mmsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmsalirActionPerformed(evt);
            }
        });
        jMenu1.add(mmsalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mInscripcionesActionPerformed


    }//GEN-LAST:event_mInscripcionesActionPerformed

    private void abminscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abminscripcionesActionPerformed
        FrInscripciones ins = new FrInscripciones();
        escritorio.add(ins);
        //codigo para centrar ventana
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = ins.getSize();
        ins.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        ins.setVisible(true);
        escritorio.moveToFront(ins);        // TODO add your handling code here:
        ins.show();
    }//GEN-LAST:event_abminscripcionesActionPerformed

    private void MenuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAlumnoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAlumnoActionPerformed

    private void abmAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmAlumnoActionPerformed
        FrAlumno fal = new FrAlumno();
        escritorio.add(fal);
        //codigo para centrar ventana
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = fal.getSize();
        fal.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        fal.setVisible(true);
        escritorio.moveToFront(fal);        // TODO add your handling code here:
        fal.show();
    }//GEN-LAST:event_abmAlumnoActionPerformed

    private void mnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnotasActionPerformed

    }//GEN-LAST:event_mnotasActionPerformed

    private void mmodificaNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmodificaNotasActionPerformed
        FrNotas fNotas = new FrNotas();
        escritorio.add(fNotas);
        //codigo para centrar ventana
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = fNotas.getSize();
        fNotas.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        fNotas.setVisible(true);
        escritorio.moveToFront(fNotas);        // TODO add your handling code here:
        fNotas.show();        // TODO add your handling code here:
    }//GEN-LAST:event_mmodificaNotasActionPerformed

    private void mmsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmsalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_mmsalirActionPerformed

    private void mlistadoalumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlistadoalumnosActionPerformed
        FrMateriaal flista = new FrMateriaal();
        escritorio.add(flista);
        //codigo para centrar ventana
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = flista.getSize();
        flista.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        flista.setVisible(true);
        escritorio.moveToFront(flista);        // TODO add your handling code here:
        flista.show();        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_mlistadoalumnosActionPerformed

    private void mmMuestraAlxMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmMuestraAlxMatActionPerformed
        FrAlumnosxMateria fmalum = new FrAlumnosxMateria();
        escritorio.add(fmalum);
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = fmalum.getSize();
        fmalum.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        fmalum.setVisible(true);
        escritorio.moveToFront(fmalum);        // TODO add your handling code here:
        fmalum.show();        // TODO add your handling code here:
        
    }//GEN-LAST:event_mmMuestraAlxMatActionPerformed

    private void mmabmMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmabmMatActionPerformed
         FrMateria fmat = new FrMateria();
        escritorio.add(fmat);
        Dimension tamescritorio = escritorio.getSize();
        Dimension tamframe = fmat.getSize();
        fmat.setLocation((tamescritorio.width - tamframe.width) / 2, (tamescritorio.height - tamframe.height) / 2);
        //.------------------

        fmat.setVisible(true);
        escritorio.moveToFront(fmat);        // TODO add your handling code here:
        fmat.show();      
    }//GEN-LAST:event_mmabmMatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAlumno;
    private javax.swing.JMenuItem abmAlumno;
    private javax.swing.JMenuItem abminscripciones;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mInscripciones;
    private javax.swing.JMenu mMateria;
    private javax.swing.JMenuItem mlistadoalumnos;
    private javax.swing.JMenuItem mmMuestraAlxMat;
    private javax.swing.JMenuItem mmabmMat;
    private javax.swing.JMenuItem mmodificaNotas;
    private javax.swing.JMenuItem mmsalir;
    private javax.swing.JMenu mnotas;
    // End of variables declaration//GEN-END:variables
}
